import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import { readLocalSupabaseEnvironment } from "../local-supabase.mjs";

test("announcement modal preserves edits and saves drafts before publishing", async ({ page }) => {
  test.skip(process.env.JOURNEY_ANNOUNCEMENT_TESTS !== "true", "Requires isolated local Supabase.");
  const local = readLocalSupabaseEnvironment("Announcement editor test");
  const admin = createClient(local.API_URL, local.SERVICE_ROLE_KEY, { auth: { persistSession: false } });
  const suffix = randomUUID();
  const email = `announcement-${suffix}@example.test`;
  const password = `Announcement-${suffix}!`;
  const title = `Announcement ${suffix.slice(0, 8)}`;
  const { data, error } = await admin.auth.admin.createUser({ email, password, email_confirm: true, user_metadata: { full_name: "Announcement test" } });
  expect(error).toBeNull();
  const userId = data.user.id;
  try {
    expect((await admin.from("users").update({ membership_status: "active" }).eq("id", userId)).error).toBeNull();
    expect((await admin.from("user_roles").upsert({ user_id: userId, role: "committee" }, { onConflict: "user_id" })).error).toBeNull();
    await page.goto("/signin?method=password&next=%2Fadmin%2Fannouncements");
    const signIn = page.locator(".auth-flip-back form");
    await signIn.locator('[name="email"]').fill(email);
    await signIn.locator('[name="password"]').fill(password);
    await signIn.getByRole("button", { name: /Sign in securely/ }).click();
    await page.waitForURL("**/admin/announcements");
    const create = page.getByRole("button", { name: "Create announcement", exact: true });
    await create.click();
    const dialog = page.getByRole("dialog");
    await dialog.getByRole("textbox", { name: "Title", exact: true }).fill(title);
    await dialog.getByRole("textbox", { name: "Description", exact: true }).fill("The workshop is closed on Sunday.\n\nPlease use the main entrance.");
    page.once("dialog", confirmation => confirmation.dismiss());
    await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
    await expect(dialog).toBeVisible();
    await expect(dialog.getByRole("textbox", { name: "Title", exact: true })).toHaveValue(title);
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.screenshot({ path: "/tmp/ydsme-announcement-desktop.png" });
    await page.setViewportSize({ width: 390, height: 844 });
    const publish = dialog.getByRole("button", { name: "Publish announcement", exact: true });
    await expect(publish).toBeInViewport();
    expect(await publish.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
    expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
    await page.screenshot({ path: "/tmp/ydsme-announcement-mobile.png" });
    await page.route("**/admin/announcements", route => route.request().method() === "POST" ? route.abort() : route.continue());
    await dialog.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(dialog.getByRole("alert")).toContainText("could not be saved");
    await expect(dialog.getByRole("textbox", { name: "Title", exact: true })).toHaveValue(title);
    await page.unroute("**/admin/announcements");
    await dialog.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(dialog).not.toBeVisible();
    await page.waitForURL(/status=draft/);
    const draft = await admin.from("announcements").select("id,lifecycle_status,body").eq("created_by", userId).single();
    expect(draft.error).toBeNull();
    expect(draft.data.lifecycle_status).toBe("draft");
    expect(draft.data.body.replace(/\r/g, "")).toContain("\n\n");
    await page.locator(".admin-list article").filter({ hasText: title }).getByRole("button", { name: "Edit", exact: true }).click();
    await expect(dialog.getByRole("textbox", { name: "Title", exact: true })).toHaveValue(title);
    await dialog.getByRole("button", { name: "Publish announcement", exact: true }).click();
    await page.waitForURL(/status=published/);
    const published = await admin.from("announcements").select("lifecycle_status,published_at").eq("id", draft.data.id).single();
    expect(published.data.lifecycle_status).toBe("published");
    expect(published.data.published_at).toBeTruthy();
    await create.click();
    await expect(dialog.getByRole("textbox", { name: "Title", exact: true })).toHaveValue("");
    await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
    await expect(create).toBeFocused();
  } finally {
    await admin.from("announcements").delete().eq("created_by", userId);
    await admin.from("audit_logs").delete().eq("actor_user_id", userId);
    await admin.auth.admin.deleteUser(userId);
  }
});
