import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import sharp from "sharp";
import { readLocalSupabaseEnvironment } from "../local-supabase.mjs";

test("creates and edits events with required artwork and conditional booking", async ({ page }) => {
  test.skip(process.env.JOURNEY_EVENT_TESTS !== "true", "Enable JOURNEY_EVENT_TESTS with local Supabase.");
  const local = readLocalSupabaseEnvironment("Event editor browser test");
  const admin = createClient(local.API_URL, local.SERVICE_ROLE_KEY, { auth: { persistSession: false } });
  const suffix = randomUUID();
  const email = `event-editor-${suffix}@example.test`;
  const password = `Event-test-${suffix}!`;
  const name = `Event editor ${suffix}`;
  const { data, error } = await admin.auth.admin.createUser({ email, password, email_confirm: true, user_metadata: { full_name: "Event editor test" } });
  expect(error).toBeNull();
  const userId = data.user.id;
  try {
    expect((await admin.from("users").update({ membership_status: "active" }).eq("id", userId)).error).toBeNull();
    expect((await admin.from("user_roles").upsert({ user_id: userId, role: "committee" }, { onConflict: "user_id" })).error).toBeNull();
    await page.goto("/signin?method=password&next=%2Fadmin%2Fevents");
    const signIn = page.locator(".auth-flip-back form");
    await signIn.locator('[name="email"]').fill(email);
    await signIn.locator('[name="password"]').fill(password);
    await signIn.getByRole("button", { name: /Sign in securely/ }).click();
    await page.waitForURL("**/admin/events");
    await page.getByRole("button", { name: "Create event", exact: true }).click();
    const dialog = page.getByRole("dialog");
    await dialog.getByLabel("Event name", { exact: true }).fill(name);
    const description = dialog.getByRole("textbox", { name: "Description", exact: true });
    const polish = dialog.getByRole("button", { name: "Polish this", exact: true });
    await expect(polish).toBeDisabled();
    await expect(description).toHaveAttribute("placeholder", /Rough notes are fine/);
    await description.fill("a".repeat(49));
    await expect(polish).toBeDisabled();
    const rough = "Join our members for an afternoon of railway maintenance and conversation.";
    await description.fill(rough);
    await expect(polish).toBeEnabled();
    const polished = "Join fellow members for railway maintenance.\n\nEnjoy an afternoon of conversation.";
    await page.route("**/api/events/polish", route => route.fulfill({ json: { description: polished } }));
    await polish.click();
    await expect(dialog.getByRole("button", { name: "Use this wording" })).toBeVisible();
    await expect(description).toHaveValue(rough);
    await dialog.getByRole("button", { name: "Use this wording" }).click();
    await expect(description).toHaveValue(polished);
    await page.unroute("**/api/events/polish");
    await page.route("**/api/events/polish", route => route.fulfill({ status: 503, json: { error: "AI polishing has not been configured yet." } }));
    await polish.click();
    await expect(dialog.getByRole("alert")).toContainText("not been configured");
    await expect(description).toHaveValue(polished);
    await page.unroute("**/api/events/polish");

    let finishPolishing;
    const heldResponse = new Promise(resolve => { finishPolishing = resolve; });
    await page.route("**/api/events/polish", async route => { await heldResponse; await route.fulfill({ json: { description: "An outdated suggestion." } }); });
    await polish.click();
    await expect(dialog.getByRole("button", { name: "Polishing…" })).toBeDisabled();
    await description.fill(rough + " Bring your tools.");
    finishPolishing();
    await expect(polish).toBeEnabled();
    await expect(dialog.getByRole("button", { name: "Use this wording" })).toHaveCount(0);
    await expect(description).toHaveValue(rough + " Bring your tools.");
    await page.unroute("**/api/events/polish");
    await dialog.getByRole("textbox", { name: "Description", exact: true }).fill("A railway event with responsive artwork.");
    await dialog.getByLabel("Date", { exact: true }).fill("2027-06-10");
    await dialog.getByLabel("Start time", { exact: true }).fill("14:00");
    await dialog.getByLabel("End time", { exact: true }).fill("13:00");
    await expect(dialog.getByLabel("End date", { exact: true })).toHaveCount(0);
    await expect(dialog.getByLabel("Do visitors need to book?")).toHaveCount(0);
    await expect(dialog.getByLabel("Event name", { exact: true })).toHaveValue(name);
    await dialog.getByRole("button", { name: "Next: event image", exact: true }).click();
    await expect(dialog.getByRole("alert")).toContainText("must end after");
    await dialog.getByLabel("End time", { exact: true }).fill("16:00");
    await expect(dialog.locator('input[type="file"]')).toBeHidden();
    await expect(dialog.getByRole("button", { name: "Save draft", exact: true })).toHaveCount(0);
    await dialog.getByLabel("Add this members-only event to the public events page").check();
    await expect(dialog.getByLabel("Add this members-only event to the public events page")).toBeChecked();
    await dialog.getByLabel("Add this members-only event to the public events page").uncheck();
    await expect(dialog.getByLabel("Add this members-only event to the public events page")).not.toBeChecked();
    await dialog.getByRole("button", { name: "Next: event image", exact: true }).click();
    await expect(dialog.getByLabel("Event name", { exact: true })).toBeHidden();
    await dialog.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(dialog.getByRole("alert").last()).toContainText("Add an event image");
    await dialog.getByRole("button", { name: "Back to details", exact: true }).click();
    await expect(dialog.locator(".event-editor-footer [role=alert]")).toHaveCount(0);
    await expect(dialog.getByLabel("Event name", { exact: true })).toHaveValue(name);
    await dialog.getByLabel("Who can attend?").selectOption("public");
    await dialog.getByLabel("Do visitors need to book?").selectOption("website");
    await dialog.getByLabel("Visitor capacity").fill("75");
    await dialog.getByLabel("Who can attend?").selectOption("member_only");
    await expect(dialog.getByLabel("Visitor capacity")).toHaveCount(0);
    await dialog.getByLabel("Runs over several days").check();
    await dialog.getByLabel("End date", { exact: true }).fill("2027-06-11");
    await dialog.getByLabel("Runs over several days").uncheck();
    await dialog.getByRole("button", { name: "Next: event image", exact: true }).click();
    await dialog.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(dialog.locator(".event-editor-footer [role=alert]")).toContainText("Add an event image");
    const image = await sharp({ create: { width: 1800, height: 1200, channels: 3, background: "#486757" } }).png().toBuffer();
    await dialog.locator('input[type="file"]').setInputFiles({ name: "event.png", mimeType: "image/png", buffer: image });
    await expect(dialog.getByRole("heading", { name, exact: true })).toBeVisible();
    await expect(dialog.locator(".event-editor-footer [role=alert]")).toHaveCount(0);
    await dialog.getByText("Need help creating an image?", { exact: true }).click();
    await expect(dialog.getByLabel("AI image generator prompt")).toHaveValue(/desktop, tablet and mobile/);
    await dialog.getByRole("button", { name: "Back to details", exact: true }).click();
    await expect(dialog.getByLabel("Event name", { exact: true })).toHaveValue(name);
    await dialog.getByRole("button", { name: "Next: event image", exact: true }).click();
    await expect(dialog.getByRole("heading", { name, exact: true })).toBeVisible();
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(dialog.getByRole("button", { name: "Save draft", exact: true })).toBeVisible();
    const draftButton = dialog.getByRole("button", { name: "Save draft", exact: true });
    const buttonBox = await draftButton.boundingBox();
    expect(buttonBox.width).toBeGreaterThan(120);
    expect(buttonBox.height).toBeLessThan(80);
    await page.screenshot({ path: "/tmp/ydsme-event-mobile.png" });
    await page.route("**/storage/v1/object/upload/sign/**", route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ message: "Test upload interruption" }) }));
    await draftButton.click();
    await expect(dialog.getByRole("alert").last()).toContainText("Upload failed");
    await expect(dialog.getByLabel("Event name", { exact: true })).toHaveValue(name);
    await page.unroute("**/storage/v1/object/upload/sign/**");
    await dialog.getByRole("button", { name: "Save draft", exact: true }).click();
    await page.waitForURL(/notice=event-draft-saved/);
    const draft = await admin.from("events").select("*").eq("host", userId).single();
    expect(draft.error).toBeNull();
    expect(draft.data.lifecycle_status).toBe("draft");
    expect(draft.data.end_date).toBe(draft.data.start_date);
    expect(draft.data.booking_mode).toBe("none");
    expect(draft.data.file_url).toMatch(/^images\/events\//);
    await page.setViewportSize({ width: 1280, height: 900 });
    const card = page.locator(".event-admin-list article").filter({ hasText: name });
    await card.getByRole("button", { name: "Edit", exact: true }).click();
    await dialog.getByLabel("Who can attend?").selectOption("public");
    await dialog.getByLabel("Do visitors need to book?").selectOption("website");
    await dialog.getByLabel("Visitor capacity").fill("75");
    await page.screenshot({ path: "/tmp/ydsme-event-desktop.png" });
    await dialog.getByRole("button", { name: "Next: event image", exact: true }).click();
    await dialog.getByRole("button", { name: "Publish event", exact: true }).click();
    await page.waitForURL(/notice=event-published/);
    const published = await admin.from("events").select("*").eq("id", draft.data.id).single();
    expect(published.data.lifecycle_status).toBe("published");
    expect(published.data.booking_capacity).toBe(75);
    expect(published.data.file_url).toBe(draft.data.file_url);
    await card.getByRole("button", { name: "Duplicate", exact: true }).click();
    await expect(dialog.getByLabel("Date", { exact: true })).toHaveValue("");
    await expect(dialog.getByRole("textbox", { name: "Description", exact: true })).toHaveValue(published.data.descriptions.replace(/\r\n/g, "\n"));
    await expect(dialog.getByLabel("Visitor capacity")).toHaveValue("75");
    await dialog.getByLabel("Date", { exact: true }).fill("2027-07-10");
    await dialog.getByRole("button", { name: "Next: event image", exact: true }).click();
    await expect(dialog.getByRole("button", { name: "Cancel event", exact: true })).toHaveCount(0);
    await dialog.getByRole("button", { name: "Save draft", exact: true }).click();
    await page.waitForURL(/notice=event-draft-saved/);
    const duplicate = await admin.from("events").select("*").eq("host", userId).neq("id", published.data.id).single();
    expect(duplicate.error).toBeNull();
    expect(duplicate.data.lifecycle_status).toBe("draft");
    expect(duplicate.data.start_date).toBe("2027-07-10");
    expect(duplicate.data.file_url).not.toBe(published.data.file_url);
    expect(duplicate.data.booking_capacity).toBe(75);
    const original = await admin.from("events").select("*").eq("id", published.data.id).single();
    expect(original.data).toEqual(published.data);
    const originalImage = await admin.storage.from("images").download(published.data.file_url.slice(7));
    const copiedImage = await admin.storage.from("images").download(duplicate.data.file_url.slice(7));
    expect(originalImage.error).toBeNull();
    expect(copiedImage.error).toBeNull();
    expect(Buffer.from(await copiedImage.data.arrayBuffer())).toEqual(Buffer.from(await originalImage.data.arrayBuffer()));
  } finally {
    const { data: events } = await admin.from("events").select("file_url").eq("host", userId);
    await admin.from("events").delete().eq("host", userId);
    for (const event of events || []) if (event.file_url?.startsWith("images/events/")) await admin.storage.from("images").remove([event.file_url.slice(7)]);
    await admin.from("audit_logs").delete().eq("actor_user_id", userId);
    await admin.auth.admin.deleteUser(userId);
  }
});
