import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import { readLocalSupabaseEnvironment } from "../local-supabase.mjs";

test("membership workspace shows one job per screen and keeps old links working", async ({ page }) => {
  test.skip(process.env.JOURNEY_MEMBERSHIP_WORKSPACE !== "true", "Requires local Supabase.");
  const local = readLocalSupabaseEnvironment("Membership workspace");
  const admin = createClient(local.API_URL, local.SERVICE_ROLE_KEY, { auth: { persistSession: false } });
  const suffix = randomUUID();
  const email = `workspace-${suffix}@example.test`;
  const password = `Workspace-${suffix}!`;
  const { data, error } = await admin.auth.admin.createUser({ email, password, email_confirm: true, user_metadata: { full_name: "Workspace test" } });
  expect(error).toBeNull();
  const id = data.user.id;
  try {
    expect((await admin.from("user_roles").upsert({user_id:id,role:"administrator"},{onConflict:"user_id"})).error).toBeNull();
    await page.goto("/signin?method=password&next=%2Fadmin%2Fmemberships");
    const signIn = page.locator(".auth-flip-back form");
    await signIn.locator('[name="email"]').fill(email);
    await signIn.locator('[name="password"]').fill(password);
    await signIn.getByRole("button", { name:/Sign in securely/ }).click();
    await page.waitForURL("**/admin/memberships");
    const tabs = page.getByRole("navigation", {name:"Membership workspace"});
    await expect(tabs.getByRole("link")).toHaveCount(4);
    await expect(page.getByRole("heading",{name:"Inbox",exact:true})).toBeVisible();
    await expect(page.getByRole("navigation",{name:"Filter tasks"})).toBeVisible();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await tabs.getByRole("link",{name:/^Members/}).click();
    await expect(page).toHaveURL(/\/admin\/memberships\/members$/);
    await expect(page.getByRole("textbox",{name:"Find a membership"})).toBeVisible();
    await page.getByRole("link",{name:"Add membership",exact:true}).click();
    await expect(page).toHaveURL(/add=member/);
    const panel = page.getByRole("dialog");
    await expect(panel.locator("form.membership-manual-create-form")).toBeVisible();
    await panel.getByRole("button",{name:"Close panel"}).click();
    await expect(page).toHaveURL(/\/admin\/memberships\/members$/);
    await expect(panel).toHaveCount(0);
    await tabs.getByRole("link",{name:/^Renewals/}).click();
    await expect(page.locator("#renewals")).toBeVisible();
    await tabs.getByRole("link",{name:/^Setup/}).click();
    await expect(page.getByRole("heading",{name:"Membership types and annual fees"})).toBeVisible();
    const setup = page.getByRole("navigation",{name:"Setup sections"});
    await setup.getByRole("link",{name:"Reports"}).click();
    await expect(page.getByRole("button",{name:"Prepare records download"})).toBeVisible();
    // Stored links from before the redesign still reach the right screen.
    await page.goto("/admin/memberships?section=renewals#renewals");
    await expect(page).toHaveURL(/\/admin\/memberships\/renewals/);
    await page.goto("/admin/memberships?view=members");
    await expect(page).toHaveURL(/\/admin\/memberships\/members$/);
    await page.goto("/admin/memberships?section=applications");
    await expect(page).toHaveURL(/\/admin\/memberships\?kind=payment/);
    await page.goto("/admin/memberships?section=membermojo-import");
    await expect(page).toHaveURL(/\/admin\/memberships\/setup\?tab=import/);
    await page.goto("/admin/memberships?section=plans&notice=plan-updated");
    await expect(page).toHaveURL(/\/admin\/memberships\/setup\?/);
    const carried = new URL(page.url()).searchParams;
    expect(carried.get("tab")).toBe("fees");
    expect(carried.get("notice")).toBe("plan-updated");
    await page.goto("/settings?tab=membership");
    await expect(page).toHaveURL(/\/admin\/memberships\/setup\?tab=payment/);
    await expect(page.getByRole("heading", {name:"Treasurer and offline payments"})).toBeVisible();
    expect((await admin.from("user_roles").update({role:"committee"}).eq("user_id",id)).error).toBeNull();
    expect((await admin.from("user_capabilities").insert({user_id:id,capability:"memberships.manage"})).error).toBeNull();
    await page.goto("/admin/memberships/setup?tab=payment");
    await expect(page.getByRole("button", {name:"Save a new payment-settings version"})).toBeVisible();
    await page.goto("/settings?tab=site");
    await expect(page).toHaveURL(/dashboard\?notice=not-authorised/);
    expect((await admin.from("user_capabilities").delete().eq("user_id",id)).error).toBeNull();
    await page.goto("/admin/memberships/setup?tab=payment");
    await expect(page).toHaveURL(/dashboard\?notice=not-authorised/);
    expect((await admin.from("user_roles").update({role:"administrator"}).eq("user_id",id)).error).toBeNull();
    await page.setViewportSize({width:390,height:844});
    await page.goto("/admin/memberships");
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await expect(page.getByRole("link",{name:"Add membership",exact:true})).toBeVisible();
  } finally {
    await admin.auth.admin.deleteUser(id);
  }
});
