import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import { readLocalSupabaseEnvironment } from "../local-supabase.mjs";

test("workshop modal preserves edits and saves drafts before publishing", async ({ page }) => {
  test.skip(process.env.JOURNEY_WORKSHOP_TESTS !== "true", "Requires isolated local Supabase.");
  const local = readLocalSupabaseEnvironment("Workshop editor test");
  const admin = createClient(local.API_URL, local.SERVICE_ROLE_KEY, { auth: { persistSession: false } });
  const suffix = randomUUID();
  const email = `workshop-${suffix}@example.test`;
  const password = `Workshop-${suffix}!`;
  const title = `Workshop ${suffix.slice(0, 8)}`;
  const { data, error } = await admin.auth.admin.createUser({ email, password, email_confirm: true, user_metadata: { full_name: "Workshop test" } });
  expect(error).toBeNull();
  const userId = data.user.id;
  try {
    expect((await admin.from("users").update({ membership_status: "active" }).eq("id", userId)).error).toBeNull();
    expect((await admin.from("user_roles").upsert({ user_id: userId, role: "committee" }, { onConflict: "user_id" })).error).toBeNull();
    await page.goto("/signin?method=password&next=%2Fadmin%2Fworkshops");
    const signIn = page.locator(".auth-flip-back form");
    await signIn.locator('[name="email"]').fill(email);
    await signIn.locator('[name="password"]').fill(password);
    await signIn.getByRole("button", { name: /Sign in securely/ }).click();
    await page.waitForURL("**/admin/workshops");
    const create = page.getByRole("button", { name: "Create workshop", exact: true });
    await create.click();
    const dialog = page.getByRole("dialog");
    await dialog.getByRole("textbox", { name: "Workshop title", exact: true }).fill(title);
    await dialog.getByRole("textbox", { name: "Description", exact: true }).fill("The workshop is closed on Sunday.\n\nPlease use the main entrance.");
    await dialog.getByLabel("Host", { exact: true }).fill("Workshop tutor");
    await dialog.getByLabel("Date", { exact: true }).fill("2027-03-20");
    await dialog.getByLabel("Start time", { exact: true }).fill("10:00");
    await dialog.getByLabel("End time", { exact: true }).fill("09:00");
    await dialog.getByLabel("Venue", { exact: true }).fill("Club workshop");
    await dialog.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(dialog.getByRole("alert")).toContainText("end time must be after");
    await dialog.getByLabel("End time", { exact: true }).fill("12:00");
    page.once("dialog", confirmation => confirmation.dismiss());
    await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
    await expect(dialog).toBeVisible();
    await expect(dialog.getByRole("textbox", { name: "Workshop title", exact: true })).toHaveValue(title);
    await page.setViewportSize({ width: 1440, height: 900 });
    await dialog.locator(".event-editor-panel").evaluate(el => { el.scrollTop = 0; });
    await page.screenshot({ path: "/tmp/ydsme-workshop-desktop.png" });
    await page.setViewportSize({ width: 390, height: 844 });
    const publish = dialog.getByRole("button", { name: "Publish workshop", exact: true });
    await expect(publish).toBeInViewport();
    expect(await publish.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
    expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
    await expect(dialog.locator(".event-editor-footer")).toHaveCSS("flex-direction", "column");
    await page.screenshot({ path: "/tmp/ydsme-workshop-mobile.png" });
    await page.route("**/admin/workshops", route => route.request().method() === "POST" ? route.abort() : route.continue());
    await dialog.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(dialog.getByRole("alert")).toContainText("could not be saved");
    await expect(dialog.getByRole("textbox", { name: "Workshop title", exact: true })).toHaveValue(title);
    await page.unroute("**/admin/workshops");
    await dialog.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(dialog).not.toBeVisible();
    await page.waitForURL(/status=draft/);
    const draft = await admin.from("workshops").select("id,lifecycle_status,descriptions").eq("created_by", userId).single();
    expect(draft.error).toBeNull();
    expect(draft.data.lifecycle_status).toBe("draft");
    expect(draft.data.descriptions.replace(/\r/g, "")).toContain("\n\n");
    await page.locator(".admin-list article").filter({ hasText: title }).getByRole("button", { name: "Edit", exact: true }).click();
    await expect(dialog.getByRole("textbox", { name: "Workshop title", exact: true })).toHaveValue(title);
    await page.setViewportSize({ width: 1440, height: 900 });
    await expect(dialog.locator(".editor-dialog-header>button")).toHaveCSS("width", "42px");
    await expect(dialog.getByRole("button", { name: "Save changes", exact: true })).toBeInViewport();
    await page.screenshot({ path: "/tmp/ydsme-workshop-edit-desktop.png" });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(dialog.locator(".editor-dialog-header>button")).toHaveCSS("width", "40px");
    await expect(dialog.getByRole("button", { name: "Save changes", exact: true })).toBeInViewport();
    await dialog.getByLabel("Status", { exact: true }).selectOption("published");
    await dialog.getByRole("button", { name: "Save changes", exact: true }).click();
    await page.waitForURL(/status=published/);
    const published = await admin.from("workshops").select("lifecycle_status").eq("id", draft.data.id).single();
    expect(published.data.lifecycle_status).toBe("published");
    await page.locator(".admin-list article").filter({ hasText: title }).getByRole("button", { name: "Edit", exact: true }).click();
    await dialog.getByLabel("Status", { exact: true }).selectOption("cancelled");
    await dialog.getByRole("button", { name: "Save changes", exact: true }).click();
    await page.waitForURL(/status=cancelled/);
    expect((await admin.from("workshops").select("lifecycle_status").eq("id", draft.data.id).single()).data.lifecycle_status).toBe("cancelled");
    await create.click();
    await expect(dialog.getByRole("textbox", { name: "Workshop title", exact: true })).toHaveValue("");
    await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
    await expect(create).toBeFocused();
  } finally {
    await admin.from("workshops").delete().eq("created_by", userId);
    await admin.from("audit_logs").delete().eq("actor_user_id", userId);
    await admin.auth.admin.deleteUser(userId);
  }
});
