create table "public"."participants" (
    "id" bigint generated by default as identity not null,
    "reference_id" uuid not null default gen_random_uuid(),
    "participant_id" uuid not null default auth.uid(),
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."participants" enable row level security;

create table "public"."workshops" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "descriptions" text not null,
    "date" date not null,
    "start_time" time without time zone not null,
    "end_time" time without time zone not null,
    "venue" text not null default ''::text,
    "virtual_link" text not null default ''::text,
    "host_name" text not null,
    "notes" text not null default ''::text,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid not null default auth.uid(),
    "maximum_participants" smallint not null default '20'::smallint
);


alter table "public"."workshops" enable row level security;

CREATE UNIQUE INDEX participants_pkey ON public.participants USING btree (id);

CREATE UNIQUE INDEX workshops_pkey ON public.workshops USING btree (id);

alter table "public"."participants" add constraint "participants_pkey" PRIMARY KEY using index "participants_pkey";

alter table "public"."workshops" add constraint "workshops_pkey" PRIMARY KEY using index "workshops_pkey";

alter table "public"."participants" add constraint "public_participants_reference_id_fkey" FOREIGN KEY (reference_id) REFERENCES workshops(id) ON DELETE CASCADE not valid;

alter table "public"."participants" validate constraint "public_participants_reference_id_fkey";

grant delete on table "public"."participants" to "anon";

grant insert on table "public"."participants" to "anon";

grant references on table "public"."participants" to "anon";

grant select on table "public"."participants" to "anon";

grant trigger on table "public"."participants" to "anon";

grant truncate on table "public"."participants" to "anon";

grant update on table "public"."participants" to "anon";

grant delete on table "public"."participants" to "authenticated";

grant insert on table "public"."participants" to "authenticated";

grant references on table "public"."participants" to "authenticated";

grant select on table "public"."participants" to "authenticated";

grant trigger on table "public"."participants" to "authenticated";

grant truncate on table "public"."participants" to "authenticated";

grant update on table "public"."participants" to "authenticated";

grant delete on table "public"."participants" to "service_role";

grant insert on table "public"."participants" to "service_role";

grant references on table "public"."participants" to "service_role";

grant select on table "public"."participants" to "service_role";

grant trigger on table "public"."participants" to "service_role";

grant truncate on table "public"."participants" to "service_role";

grant update on table "public"."participants" to "service_role";

grant delete on table "public"."workshops" to "anon";

grant insert on table "public"."workshops" to "anon";

grant references on table "public"."workshops" to "anon";

grant select on table "public"."workshops" to "anon";

grant trigger on table "public"."workshops" to "anon";

grant truncate on table "public"."workshops" to "anon";

grant update on table "public"."workshops" to "anon";

grant delete on table "public"."workshops" to "authenticated";

grant insert on table "public"."workshops" to "authenticated";

grant references on table "public"."workshops" to "authenticated";

grant select on table "public"."workshops" to "authenticated";

grant trigger on table "public"."workshops" to "authenticated";

grant truncate on table "public"."workshops" to "authenticated";

grant update on table "public"."workshops" to "authenticated";

grant delete on table "public"."workshops" to "service_role";

grant insert on table "public"."workshops" to "service_role";

grant references on table "public"."workshops" to "service_role";

grant select on table "public"."workshops" to "service_role";

grant trigger on table "public"."workshops" to "service_role";

grant truncate on table "public"."workshops" to "service_role";

grant update on table "public"."workshops" to "service_role";

create policy "Enable delete for users based on user_id"
on "public"."participants"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = participant_id));


create policy "Enable insert for authenticated members only"
on "public"."participants"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all authenticated members"
on "public"."participants"
as permissive
for select
to authenticated
using (true);


create policy "Enable delete for committees and admin"
on "public"."workshops"
as permissive
for delete
to authenticated
using ((authorize('committee.create'::app_permission) OR authorize('read-only-committee.create'::app_permission) OR authorize('administrator.create'::app_permission)));


create policy "Enable insert for committees and admin only"
on "public"."workshops"
as permissive
for insert
to authenticated
with check ((authorize('committee.create'::app_permission) OR authorize('read-only-committee.create'::app_permission) OR authorize('administrator.create'::app_permission)));


create policy "Enable read access for all members"
on "public"."workshops"
as permissive
for select
to authenticated
using (true);


create policy "Enable update for committees and admin"
on "public"."workshops"
as permissive
for update
to authenticated
using ((authorize('committee.create'::app_permission) OR authorize('read-only-committee.create'::app_permission) OR authorize('administrator.create'::app_permission)));



