create table "public"."configs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "short_name" text not null default ''::text,
    "full_name" text not null default ''::text,
    "registered_name" text not null default ''::text,
    "company_no" text not null default ''::text,
    "website" text not null default ''::text,
    "telephone" text not null default ''::text,
    "registered_address" jsonb not null,
    "settings" jsonb not null,
    "committees" jsonb[] not null default '{}'::jsonb[],
    "socials" jsonb[] not null default '{}'::jsonb[],
    "affiliates" jsonb[] not null default '{}'::jsonb[],
    "contacts" jsonb[] not null default '{}'::jsonb[]
);


alter table "public"."configs" enable row level security;

CREATE UNIQUE INDEX configs_pkey ON public.configs USING btree (id);

alter table "public"."configs" add constraint "configs_pkey" PRIMARY KEY using index "configs_pkey";

grant delete on table "public"."configs" to "anon";

grant insert on table "public"."configs" to "anon";

grant references on table "public"."configs" to "anon";

grant select on table "public"."configs" to "anon";

grant trigger on table "public"."configs" to "anon";

grant truncate on table "public"."configs" to "anon";

grant update on table "public"."configs" to "anon";

grant delete on table "public"."configs" to "authenticated";

grant insert on table "public"."configs" to "authenticated";

grant references on table "public"."configs" to "authenticated";

grant select on table "public"."configs" to "authenticated";

grant trigger on table "public"."configs" to "authenticated";

grant truncate on table "public"."configs" to "authenticated";

grant update on table "public"."configs" to "authenticated";

grant delete on table "public"."configs" to "service_role";

grant insert on table "public"."configs" to "service_role";

grant references on table "public"."configs" to "service_role";

grant select on table "public"."configs" to "service_role";

grant trigger on table "public"."configs" to "service_role";

grant truncate on table "public"."configs" to "service_role";

grant update on table "public"."configs" to "service_role";

create policy "Enable insert for admin"
on "public"."configs"
as permissive
for insert
to authenticated
with check (authorize('administrator.create'::app_permission));


create policy "Enable read access for all users"
on "public"."configs"
as permissive
for select
to public
using (true);


create policy "Enable update for admin"
on "public"."configs"
as permissive
for update
to authenticated
using (authorize('administrator.update'::app_permission));



