/**
* USERS ROLES AND APP PERMISSIONS
* Note: This table contains user data. Users should only be able to view and update their own data.
*/

-- Custom types
create type public.app_permission as enum (
'moderator.select',
'moderator.create',
'moderator.update',
'moderator.delete',
'committee.select',
'committee.create',
'committee.update',
'committee.delete',
'read-only-committee.select',
'read-only-committee.create',
'read-only-committee.update',
'read-only-committee.delete',
'administrator.select',
'administrator.create',
'administrator.update',
'administrator.delete'
);
create type public.app_role as enum ('member', 'moderator', 'committee',
'read-only-committee', 'administrator');

-- USER ROLES
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null,
  role      app_role not null default 'member',
  unique (user_id, role)
);
comment on table public.user_roles is 'Application roles for each user.';

-- ROLE PERMISSIONS
create table public.role_permissions (
  id           bigint generated by default as identity primary key,
  role         app_role not null,
  permission   app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is 'Application permissions for each role.';

/**
* Assign user role on account creation - default to 'member'
* Note:
*/
create function public.handle_new_user_role()
returns trigger
set search_path = ''
as $$
begin
  insert into public.user_roles (user_id, role)
  values (
    new.id,
    'member'
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created_role
  after insert on auth.users
  for each row execute procedure handle_new_user_role();

alter table "public"."role_permissions" enable row level security;

alter table "public"."user_roles" enable row level security;

create policy "Enable read access for all authenticated members"
on "public"."role_permissions"
as permissive
for select
to authenticated
using (true);

create policy "Enable read access for all members"
on "public"."user_roles"
as permissive
for select
to authenticated
using (true);



