create type "public"."feed_type" as enum ('event', 'user', 'document', 'workshop', 'message', 'broadcast');

create table "public"."feeds" (
    "id" bigint generated by default as identity not null,
    "type" feed_type not null,
    "title" text,
    "message" text not null,
    "url" text,
    "author_name" text,
    "author_id" uuid default auth.uid(),
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."feeds" enable row level security;

CREATE UNIQUE INDEX feeds_pkey ON public.feeds USING btree (id);

alter table "public"."feeds" add constraint "feeds_pkey" PRIMARY KEY using index "feeds_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.new_document_feeds()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.feeds (type, title, message, url, author_name, author_id)
  VALUES (
    'document',
    'New Document',
    CONCAT('A new ', INITCAP(REPLACE(NEW.category, '-', ' ')), ' is uploaded. Click on the link below to view the document'),
    NEW.file_url,
    NULL,
    NULL
  );
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.new_user_feeds()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.feeds (type, title, message, url, author_name, author_id)
  VALUES (
    'user',
    'We have a new member',
    CONCAT('Please welcome ', NEW.full_name, ' to the club. 😊'),
    NULL,
    NULL,
    NULL
  );
  RETURN NEW;
END;
$function$
;

grant delete on table "public"."feeds" to "anon";

grant insert on table "public"."feeds" to "anon";

grant references on table "public"."feeds" to "anon";

grant select on table "public"."feeds" to "anon";

grant trigger on table "public"."feeds" to "anon";

grant truncate on table "public"."feeds" to "anon";

grant update on table "public"."feeds" to "anon";

grant delete on table "public"."feeds" to "authenticated";

grant insert on table "public"."feeds" to "authenticated";

grant references on table "public"."feeds" to "authenticated";

grant select on table "public"."feeds" to "authenticated";

grant trigger on table "public"."feeds" to "authenticated";

grant truncate on table "public"."feeds" to "authenticated";

grant update on table "public"."feeds" to "authenticated";

grant delete on table "public"."feeds" to "service_role";

grant insert on table "public"."feeds" to "service_role";

grant references on table "public"."feeds" to "service_role";

grant select on table "public"."feeds" to "service_role";

grant trigger on table "public"."feeds" to "service_role";

grant truncate on table "public"."feeds" to "service_role";

grant update on table "public"."feeds" to "service_role";

create policy "Enable delete for members based on author_id"
on "public"."feeds"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = author_id));


create policy "Enable insert for authenticated members"
on "public"."feeds"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for authenticated members"
on "public"."feeds"
as permissive
for select
to authenticated
using (true);


CREATE TRIGGER after_user_insert AFTER INSERT ON public.documents FOR EACH ROW EXECUTE FUNCTION new_document_feeds();

CREATE TRIGGER after_user_insert AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION new_user_feeds();


