create table "public"."committees" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid,
    "name" text not null default ''::text,
    "title" text not null,
    "file_url" text not null default ''::text,
    "email" text not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid not null default auth.uid()
);


alter table "public"."committees" enable row level security;

CREATE UNIQUE INDEX committees_pkey ON public.committees USING btree (id);

alter table "public"."committees" add constraint "committees_pkey" PRIMARY KEY using index "committees_pkey";

alter table "public"."committees" add constraint "committees_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL not valid;

alter table "public"."committees" validate constraint "committees_user_id_fkey";

grant delete on table "public"."committees" to "anon";

grant insert on table "public"."committees" to "anon";

grant references on table "public"."committees" to "anon";

grant select on table "public"."committees" to "anon";

grant trigger on table "public"."committees" to "anon";

grant truncate on table "public"."committees" to "anon";

grant update on table "public"."committees" to "anon";

grant delete on table "public"."committees" to "authenticated";

grant insert on table "public"."committees" to "authenticated";

grant references on table "public"."committees" to "authenticated";

grant select on table "public"."committees" to "authenticated";

grant trigger on table "public"."committees" to "authenticated";

grant truncate on table "public"."committees" to "authenticated";

grant update on table "public"."committees" to "authenticated";

grant delete on table "public"."committees" to "service_role";

grant insert on table "public"."committees" to "service_role";

grant references on table "public"."committees" to "service_role";

grant select on table "public"."committees" to "service_role";

grant trigger on table "public"."committees" to "service_role";

grant truncate on table "public"."committees" to "service_role";

grant update on table "public"."committees" to "service_role";

create policy "Enable delete for admin"
on "public"."committees"
as permissive
for delete
to authenticated
using (authorize('administrator.delete'::app_permission));


create policy "Enable insert for admin"
on "public"."committees"
as permissive
for insert
to authenticated
with check (authorize('administrator.create'::app_permission));


create policy "Enable read access for all users"
on "public"."committees"
as permissive
for select
to public
using (true);


create policy "Enable update for admin"
on "public"."committees"
as permissive
for update
to authenticated
using (authorize('administrator.update'::app_permission));



