/**
* Events
* Note: Create event table, manage RLS access and also delete image based on
banner url
*/

create type "public"."event_type" as enum ('member_only', 'public');

create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "name" text not null default ''::text,
    "descriptions" text not null default ''::text,
    "banner_url" text not null default ''::text,
    "created_at" timestamp with time zone not null default now(),
    "start_date" date not null,
    "end_date" date not null,
    "start_time" time without time zone not null,
    "end_time" time without time zone not null,
    "event_type" event_type not null default 'public'::event_type,
    "display_in_homepage" boolean not null default false,
    "is_ticket_required" boolean not null default false,
    "reservation_link" text not null default ''::text,
    "host" uuid not null default auth.uid()
);


alter table "public"."events" enable row level security;

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.delete_banner_url()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 set search_path = ''
AS $function$BEGIN
    -- Construct the DELETE command for your storage
    DELETE FROM storage.objects WHERE bucket_id = 'images' AND name = OLD
    .banner_url;
    RETURN OLD;
END;$function$
;

CREATE OR REPLACE FUNCTION public.delete_banner_url()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
BEGIN
    -- Extract the first directory (bucket) from the banner_url
    DECLARE bucket_name TEXT;
    BEGIN
        bucket_name := split_part(OLD.banner_url, '/', 1);  -- Extract "images" or equivalent

        -- Remove the bucket_id from the banner_url
        OLD.banner_url := substring(OLD.banner_url from length(bucket_name) + 2)
        ; -- Remove "images/"

        -- Construct the DELETE command for your storage
        DELETE FROM storage.objects
        WHERE bucket_id = 'images' AND name = OLD.banner_url;

        RETURN OLD;
    END;
END;
$function$;


grant delete on table "public"."events" to "anon";

grant insert on table "public"."events" to "anon";

grant references on table "public"."events" to "anon";

grant select on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant update on table "public"."events" to "anon";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant references on table "public"."events" to "authenticated";

grant select on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";

grant delete on table "public"."events" to "service_role";

grant insert on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant select on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";

grant update on table "public"."events" to "service_role";

CREATE TRIGGER trigger_delete_banner_url AFTER DELETE ON public.events FOR EACH ROW EXECUTE FUNCTION delete_banner_url();

--Events table RLS
create policy "Enable read access for all users"
on "public"."events"
as permissive
for select
to public
using (true);

create policy "Enable update for mod, committee and admin"
on "public"."events"
as permissive
for update
to authenticated
using ((authorize('moderator.update'::app_permission) OR authorize('committee.update'::app_permission) OR authorize('read-only-committee.update'::app_permission) OR authorize('administrator.update'::app_permission)));

create policy "Enable insert for committee and administrator"
on "public"."events"
as permissive
for insert
to authenticated
with check ((authorize('moderator.create'::app_permission) OR authorize('committee.create'::app_permission) OR authorize('read-only-committee.create'::app_permission) OR authorize('administrator.create'::app_permission)));

create policy "Enable delete for mod, committees and amin"
on "public"."events"
as permissive
for delete
to public
using ((authorize('moderator.delete'::app_permission) OR authorize('committee.delete'::app_permission) OR authorize('read-only-committee.delete'::app_permission) OR authorize('administrator.delete'::app_permission)));
