-- Public announcements are authored through the server-only application DAL.
-- Anonymous visitors can read only the deliberately limited published view.

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(btrim(title)) between 2 and 26),
  body text not null check (char_length(btrim(body)) between 2 and 120),
  lifecycle_status text not null default 'draft'
    check (lifecycle_status in ('draft', 'published', 'archived')),
  created_by uuid not null references auth.users(id) on delete restrict,
  published_at timestamptz,
  archived_at timestamptz,
  archived_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (lifecycle_status <> 'published' or published_at is not null)
);

create index if not exists announcements_publication_idx
  on public.announcements (published_at desc, id desc)
  where lifecycle_status = 'published';

alter table public.announcements enable row level security;

revoke all on table public.announcements from public, anon, authenticated;
grant select, insert, update, delete on table public.announcements to service_role;
revoke all on sequence public.announcements_id_seq from public, anon, authenticated;
grant usage, select on sequence public.announcements_id_seq to service_role;

create or replace view public.public_announcements
with (security_barrier = true)
as
select id, title, body, published_at, updated_at
from public.announcements
where lifecycle_status = 'published'
  and published_at <= now();

revoke all on public.public_announcements from public, anon, authenticated;
grant select on public.public_announcements to anon, authenticated;
