-- Normalize ordered public links and donation campaigns while retaining the
-- legacy config columns during the expand/contract observation period.

create table if not exists public.site_social_links (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null default '',
  position integer not null check (position >= 0)
);
create table if not exists public.site_affiliates (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null default '',
  logo_path text not null default '',
  position integer not null check (position >= 0)
);
create table if not exists public.donation_campaigns (
  kind text primary key check (kind in ('generic', 'target')),
  enabled boolean not null default false,
  title text not null,
  description text not null,
  button_label text not null,
  target_pence bigint not null default 0 check (target_pence >= 0),
  updated_at timestamptz not null default now()
);

insert into public.site_social_links (name, url, position)
select item->>'name', coalesce(item->>'link', ''), ordinal::integer - 1
from public.configs c, unnest(c.socials) with ordinality as link(item, ordinal)
where not exists (select 1 from public.site_social_links)
  and coalesce(item->>'name', '') <> '';

insert into public.site_affiliates (name, url, logo_path, position)
select item->>'name', coalesce(item->>'website', ''), coalesce(item->>'logo', ''), ordinal::integer - 1
from public.configs c, unnest(c.affiliates) with ordinality as affiliate(item, ordinal)
where not exists (select 1 from public.site_affiliates)
  and coalesce(item->>'name', '') <> '';

insert into public.donation_campaigns (kind, enabled, title, description, button_label, target_pence)
select 'generic',
  coalesce((settings #>> '{donations,generic,enabled}')::boolean, false),
  coalesce(settings #>> '{donations,generic,title}', 'Help keep steam in motion.'),
  coalesce(settings #>> '{donations,generic,description}', 'Support the Society.'),
  coalesce(settings #>> '{donations,generic,buttonLabel}', 'Make a donation'),
  0
from public.configs limit 1
on conflict (kind) do nothing;

insert into public.donation_campaigns (kind, enabled, title, description, button_label, target_pence)
select 'target',
  coalesce((settings #>> '{donations,target,enabled}')::boolean, false),
  coalesce(settings #>> '{donations,target,title}', 'Help us reach our next milestone.'),
  coalesce(settings #>> '{donations,target,description}', 'Support a focused Society project.'),
  coalesce(settings #>> '{donations,target,buttonLabel}', 'Support this project'),
  coalesce((settings #>> '{donations,target,targetPence}')::bigint, 500000)
from public.configs limit 1
on conflict (kind) do nothing;

alter table public.site_social_links enable row level security;
alter table public.site_affiliates enable row level security;
alter table public.donation_campaigns enable row level security;
revoke all on public.site_social_links, public.site_affiliates, public.donation_campaigns from public, anon, authenticated;
grant select, insert, update, delete on public.site_social_links, public.site_affiliates, public.donation_campaigns to service_role;

create or replace view public.public_site_links
with (security_invoker = true)
as
  select 'social'::text as link_type, name, url, ''::text as logo_path, position
  from public.site_social_links
  union all
  select 'affiliate'::text, name, url, logo_path, position
  from public.site_affiliates;

grant select on public.public_site_links to anon, authenticated;
create policy ydsme_public_social_links_read on public.site_social_links for select to anon, authenticated using (true);
create policy ydsme_public_affiliates_read on public.site_affiliates for select to anon, authenticated using (true);
